/** A listázók szűrőjének azonosítására szolgáló enum */
export enum FilterStateListEnum {
  ACCOUNT_CONFIG = 'ACCOUNT_CONFIG',

  CATEGORY = 'CATEGORY',

  COMPANY = 'COMPANY',

  DEMAND = 'DEMAND',

  PROPER_PACKAGES = 'PROPER_PACKAGES',

  INFORMATION_CURRENCY = 'INFORMATION_CURRENCY',

  INFORMATION_TYPE = 'INFORMATION_TYPE',

  INFORMATION_UNIT = 'INFORMATION_UNIT',

  LABEL = 'LABEL',

  NOTIFICATION = 'NOTIFICATION',

  SYSTEM_NOTIFICATION = 'SYSTEM_NOTIFICATION',

  NOTIFICATION_TEMPLATE = 'NOTIFICATION_TEMPLATE',

  SELECT_RECIPIENTS = 'SELECT_RECIPIENTS',

  PARTNER = 'PARTNER',

  PURCHASE = 'PURCHASE',

  PURCHASE_DEMAND = 'PURCHASE_DEMAND',

  TRANSACTION_HISTORY = 'TRANSACTION_HISTORY',

  RATING = 'RATING',

  DERIVED_TYPE = 'DERIVED_TYPE',

  DERIVED_UNIT = 'DERIVED_UNIT',

  PACKAGE = 'PACKAGE',

  SHARE = 'SHARE',

  SHARE_DEMAND = 'SHARE_DEMAND',

  SUPPLY = 'SUPPLY',
}
